module Bitcoin
  class Point
    type number = Integer | FieldElement
    def initialize: (x: number?, y: number?, a: number, b: number) -> untyped

    attr_reader x: number?
    attr_reader y: number?
    attr_reader a: number
    attr_reader b: number

    def ==: (Point) -> bool
    def +: (Point) -> Point
    def *: (Integer) -> Point
  end
end
