module Bitcoin
  class Point
    def initialize: (x: Integer?, y: Integer?, a: Integer, b: Integer) -> untyped

    attr_reader x: Integer?
    attr_reader y: Integer?
    attr_reader a: Integer
    attr_reader b: Integer

    def ==: (Point) -> bool
    def +: (Point) -> Point
    def -: (Point) -> Point
    def *: (Point) -> Point
    def **: (Integer) -> Point
  end
end
